#!/usr/bin/env python
# -*- coding: utf-8 -*-
from collections import defaultdict

PGtable = {
    'VERB':{
        # Chapter 1: Simple Patterns
        'V n':['V sth'],
        # 'V pl-n':['V sth+s'],
        'V pron-refl':['V oneself'],
        'V amount':['V amount'],
        'V adj':['V adjp'],
        'V -ing':['V doing'],
        'V to-inf':['V to inf'],
        'V inf':['V inf'],
        'V that':['V that'],
        'V wh':['V wh'],
        'V wh-to-inf':['V wh to inf'],
        'V with quote':['quote V', 'quote sth V', 'V quote'],
        'V so/not':['V so', 'V not'],
        'V as if':['V as if'],
        'V as though':['V as though'],
        'V and v':['V and do'],
        # Chapter 2: Simple Patterns with Prepositions and Adverbs
        # 'V prep/adv, V adv/prep':['V adv', 'V prep]
        'V adv':['V advp'],
        # 'pl-n V together':['sth+s V together'],
        # 'pl-n V P together':['sth+s V prep together'],        
        'n V together':['sth V together'],
        'n V P together':['sth V prep together'],
        # 'V prep':['V prep'],
        'V about n':['V about sth'],
        'V across n':['V across sth'],
        'V after n':['V after sth'],
        'V against n':['V against sth'],
        'V around/round n':['V around sth', 'V round sth'],
        'V as adj.':['V as adjp'],
        'V as n':['V as sth'],
        'V as to wh':['V as to wh'],
        'V at n':['V at n'],
        # 'V between pl-n':['V between sth+s'],
        'V between n':['V between sth'],
        'V by amount':['V by amount'],
        'V by -ing':['V by doing'],
        'V by n':['V by sth'],
        'V for n':['V for sth'],
        'V from n':['V from sth'],
        'V in n':['V in sth'],
        'V in favor of n':['V in favor of sth'],
        'V into n':['V into sth'],
        'V like n':['V like sth'],
        'V of n':['V of sth'],
        'V off n':['V off sth'],
        'V on n':['V on sth'],
        'V on to n':['V on to sth'],
        'V onto n':['V onto sth'],
        'V out of n':['V out of sth'],
        'V over n':['V over sth'],
        'V through n':['V through sth'],
        'V to n':['V to sth'],
        'V towards/toward n':['V toward sth', 'V towards sth'],
        'V under n':['V under sth'],
        'V with n':['V with sth'],
        # 'V among pl-n':['V among sth+s'],
        # 'V adj among pl-n':['V adjp among sth+s'],
        'V among n':['V among sth'],
        'V adj among n':['V adjp among sth'],
        'V before n':['V before sth'],
        'V behind n':['V behind sth'],
        'V down n':['V down sth'],
        'V past n':['V past sth'],
        # Chapter 3: Complex Patterns
        'V n n':['V sth sth'],
        'V n adj':['V sth adjp'],
        'V n -ing':['V sth doing'],
        'V n to-inf':['V sth to inf'],
        'V n inf':['V sth inf'],
        'V n wh':['V sth wh'],
        'V n wh-to-inf':['V sth wh to inf'],
        'V n with quote':['quote sth V', 'V sth quote'],
        'be V-ed with quote':['quote sth be V-ed'],
        # 'V pron-refl with quote':['quote sth with oneself'],
        'V n -ed':['V sth done'],
        # Chapter 4: Complex Patterns with Prepositions and Adverbs
        # 'V n prep/adv':['V sth prep', 'V sth adv'],
        # 'V n prep':['V sth prep'],
        'V n adv':['V sth advp'],
        'V n with adv':['V sth with advp'],
        # 'V way prep/adv':['V way prep', 'V way adv'],
        'V way prep':['V way prep'],
        'V way adv':['V way advp'],
        'V n about n':['V sth about sth'],
        'V n against n':['V sth against sth'],
        'V n as adj':['V sth as adjp'],
        'V n as n':['V sth as n'],
        'V n as to wh':['V sth as to wh'],
        'V n at n':['V sth at sth'],
        # 'V n between pl-n':['V sth between sth+s'],
        # 'V n among pl-n':['V sth among sth+s'],
        'V n between n':['V sth between sth'],
        'V n among n':['V sth among sth'],
        'V n by n':['V sth by sth'],
        'V n for n':['V sth for sth'],
        'V n from n':['V sth from sth'],
        'V n in n':['V sth in sth'],
        'V n into n':['V sth into sth'],
        'V n into -ing':['V sth into doing'],
        'V n of n':['V sth of sth'],
        'V n off n':['V sth off sth'],
        'V n on n':['V sth on sth'],
        'V n onto n':['V sth onto sth'],
        'V n on to n':['V sth on to sth'],
        'V n over n':['V sth over sth'],
        'V n to n':['V sth to sth'],
        'V n towards/toward n':['V sth toward sth', 'V sth towards sth'],
        'V n with n':['V sth with sth'],
        'V n after n':['V sth after sth'],
        'V n around n':['V sth around sth'],
        'V n round n':['V sth round sth'],
        'V n before n':['V sth before sth'],
        'V n through n':['V sth through sth'],
        # Chapter 9: Verb Patterns with it
        # 1. Introductory it as Subject
        # 'it V clause':['it V clause'],
        'it V that':['it V that'],
        'it V to-inf':['it V to inf'],
        'it V wh':['it V wh'],
        'it V that':['it V that'],
        'it V when':['it V when'],
        'it V if':['it V if'],
        'it V as if':['it V as if'],
        'it V as though':['it V as though'],
        'it V like':['it V like'],
        # 'it V to n clause':['it V to sth clause'],
        'it V to n that':['it V to sth that'],
        'it V to n to-inf':['it V to sth to inf'],
        'it V to n wh':['it V to sth wh'],
        'it V to n as if':['it V to sth as if'],
        'it V to n as though':['it V to sth as though'],
        'it V to n like':['it V to sth like'],
        # 'it V prep clause':['it V prep clause'],
        'it V prep that':['it V prep that'],
        'it V prep to-inf':['it V prep to inf'],
        # 'it be V-ed clause':['it be done clause'],
        'it be V-ed that':['it be V-ed that'],
        'it be V-ed to-inf':['it be V-ed to inf'],
        'it be V-ed wh':['it be V-ed wh'],
        # 'it V n clause':['it V sth clause'],
        'it V n that':['it V sth that'],
        'it V n to-inf':['it V sth to inf'],
        'it V n wh':['it V sth wh'],
        'it V n when':['it V sth when'],
        'it V n if':['it V sth if'],
        'it V n -ing':['it V sth doing'],
        'it V n before':['it V sth before'],
        'it V amount brfore':['it V sth before'],
        'it V n since':['it V sth since'],
        'it V amount since':['it V sth since'],
        'it V n for n to-inf':['it V sth for sth to inf'],
        'it V n n to-inf':['it V sth sth to inf'],
        'it V amount for n that':['it V amount for sth that'],
        'it V n adj that':['it V sth adjp that'],
        'it V n adj to-inf':['it V sth adjp to inf'],
        # 'it V adj clause':['it V adj clause'],
        'it V adj that':['it V adj that'],
        'it V adj to-inf':['it V adj to inf'],
        'it V adj wh':['it V adj wh'],
        'it V adj when':['it V adj when'],
        'it V adj if':['it V adj if'],
        'it V adj -ing':['it V adj doing'],
        'it V adj of n to-inf':['it V adj of sth to inf'],
        'it V adj for n to-inf':['it V adj for sth to inf'],
        # 2. Introductory it as Object
        # 'V it clause':['V it clause'],
        'V it that':['V it that'],
        'V it when':['V it when'],
        'V it if':['V it if'],
        # 'V it to n clause':['V it to sth clause'],
        'V it to n that':['V it to sth that'],
        'V it to n to-inf':['V it to sth to inf'],
        # 'V it as n/adj clause':['V it as sth clause', 'V it as adj clause'],
        'V it as n that':['V it as sth clause'],
        'V it as adj that':['V it as adjp that'],        
        'V it as n to-inf':['V it as sth to inf'],
        'V it as adj to-inf':['V it as adjp to inf'],
        'V it as n when':['V it as sth when'],
        'V it as adj when':['V it as adjp when'],        
        'V it as n if':['V it as sth if'],
        'V it as adj if':['V it as adjp if'],
        # 'V it n clause':['V it sth clause']
        'V it n that':['V it sth that'],
        'V it n to-inf':['V it sth to inf'],
        'V it n when':['V it sth when'],
        'V it n if':['V it sth if'],
        # 'V it adj clause':['V it adjp clause']
        'V it adj that':['V it adjp that'],
        'V it adj to-inf':['V it adjp to inf'],
        'V it adj wh':['V it adjp wh'],
        'V it adj when':['V it adjp when'],
        'V it adj if':['V it adjp if'],
        # 3. General it as Subject
        'it V':['it V'],
        'it V adj':['it V adjp'],
        'it V adj prep':['it V adj prep'],
        'it V adj adv':['it V adj advp'],
        'it V n':['it V sth'],
        'it V to n':['it V to sth'],
        'it V towards n':['it V towards sth'],
        'it V prep that':['it V prep that'],
        'it V adv that':['it V advp that'],
        # 4. General it as Object
        'V it':['V it'],
        # 'pl-n V it P':['sth+s V it'],
        'n V it P':['sth V it PRT'],
        'V it P with n':['V it PRT with n'],
        'V it prep':['V it prep'],
        'V it adv':['V it advp'],
        'V it adj':['V it adj'],
        'V it n':['V it sth'],
        'V it -ed':['V it done'],
        'V it inf':['V it inf'],
        'V it over n':['V it over sth'],
        'V it to n':['V it to sth'],
        'V it P P n':['V it prep prep sth'],
        'V prep it':['V prep it'],
        'V n for it':['V sth for it'],
    },
    'NOUN':{
        'N that':['N that'],
        'N to-inf':['N to inf'],
        'the N to-inf':['the N to inf'],
        'N for n to-inf':['N for sth to inf'],
        'N to n to-inf':['N to sth to inf'],
        'v-link N to-inf':['v-link N to inf'],
        'v-link adj N to-inf':['v-link adj N to inf'],
        # 'N about n':['N about sth', 'N about doing', 'N about wh'],
        'N about n':['N about sth'],
        'N about -ing':['N about doing'],
        'N about wh':['N about wh'],
        # 'N against n':['N against sth', 'N against doing'],
        'N against n':['N against sth'],
        'N against -ing':['N against doing'],
        # 'N among pl-n':['N among sth+s'],
        'N among n':['N among sth'],
        'N as n':['N as sth'],
        'N of n as n':['N of sth as sth'],
        'poss N as n':["one's N as sth"],
        'v-link a N as n':['v-link a N as sth'],        
        'N as to wh':['N as to wh'],
        'N as to n':['N as to sth'],
        # 'N at n':['N at sth', 'N at doing'],
        'N at n':['N at sth'],
        'N at -ing':['N at doing'],
        'N behind n':['N behind sth'],
        # 'N between pl-n':['N between sth+s'],
        # 'N between n':['N between sth', 'N between doing'],
        'N between n':['N between sth'],
        'N between -ing':['N between doing'],
        'N by n':['N by sth'],
        # 'N for n':['N for sth', 'N for doing'],
        'N for n':['N for sth'],
        'N for -ing':['N for doing'],
        'N for n to-inf':['N for n to inf'],
        # 'N from n':['N from sth', 'N from doing'],
        'N from n':['N from sth'],
        'N from -ing':['N from doing'],
        'N from n for n':['N from sth for sth'],
        'N from n to n':['N from sth to sth'],
        'N from n that':['N from sth that'],
        'N from n to-inf':['N from sth to inf'],
        # 'N in n':['N in sth', 'N in doing'],
        'N in n':['N in sth'],
        'N in -ing':['N in doing'],
        # 'N in favour of n':['N in favour of sth', 'N in favour of doing'],
        'N in favour of n':['N in favour of sth'],
        'N in favour of -ing':['N in favour of doing'],
        'N into n':['N into sth'],
        # 'N of n':['N of sth', 'N of doing', 'N of wh'],
        'N of n':['N of sth'],
        'N of -ing':['N of doing'],
        'N of wh':['N of wh'],
        'N of amount':['N of amount'],
        # 'N of pl-n':['N of sth+s'],
        # 'N on n':['N on sth', 'N on doing', 'N on wh'],
        'N on n':['N on sth'],
        'N on -ing':['N on doing'],
        'N on wh':['N on wh'],
        'N on n for n':['N on sth for sth'],
        'N on n to-inf n':['N on sth to inf sth'],
        # 'NOUN ord ADJ'
        # 'N over n':['N over sth', 'N over doing', 'N over wh'],
        'N over n':['N over sth'],
        'N over -ing':['N over doing'],
        'N over wh':['N over wh'],
        # 'N to n':['N to sth', 'N to doing'],
        'N to n':['N to sth'],
        'N to -ing':['N to doing'],
        'N from n to n':['N from sth to sth'],
        'N of n to n':['N of sth to sth'],
        'N to n that':['N to sth that'],
        'N to n to-inf':['N to sth to inf'],
        'of N to n':['of N to n'],
        # 'N towards/toward n':['N towards sth', 'N towards doing', 'N toward sth', 'N toward doing'],
        'N towards/toward n':['N towards sth', 'N toward sth'],
        'N towards/toward -ing':['N towards doing', 'N toward doing'],
        # 'N with n':['N with sth', 'N with doing'],
        'N with n':['N with sth'],
        'N with -ing':['N with doing'],
        'N of n with n':['N of sth with sth'],
        'N with n for n':['N with sth for sth'],
        'N with n that':['N with sth that'],
        'N with n to-inf':['N with sth to inf'],
        # 'the N':['the N'],
        'the N be that':['the N be that'],
        'the N about n be that':['the N about sth be that'],
        'the N with n be that':['the N with sth be that'],
        # 'the N be to doing n':['the N be to doing sth'],
        # "one's N":["one's N"],
        # "one's N as n":["one's N as sth"],
        "poss N be that":["one's N be that"],
        'the N be to-inf':['the N be to inf'],
        "poss N be to-inf":["one's N be to-inf"],
        'the N be -ing':['the N be doing'],
        "poss N be ing":["one's N be doing"],
        # 'it be det N doing n'
        'it v-link det N that':['it v-link det N that'],
        'it v-link N that':['it v-link det N that'],
        'it v-link a adj N that':['it v-link a adj N that'],
        'it v-link poss N that':["it v-link one's N that"],
        'it v-link det N to-inf':['it v-link det N to inf'],
        'it v-link N to-inf':['it v-link N to inf'],
        'it v-link poss N to-inf':["it v-link one's N to inf"],
        'it v N to-inf':['it do N to inf'],
        'it v n N to-inf':['it do sth N to inf'],
        'it v-link det N -ing':['it v-link det N doing'],
        'it v-link N -ing':['it v-link N doing'],
        'v it det N to-inf':['do it det N to inf'],
        'v it as det N to-inf':['do it as det N to inf'],
        'there be det N about n':['there be det N about sth'],
        'there be det N in n/-ing':['there be det N in sth', 'there be det N in doing'],
        'there be det N to n/-ing':['there be det N to sth', 'there be det N to doing'],
        'at N':['at N'],
        'by N':['by N'],
        'from N':['from N'],
        # 'from N to N':['from N to sth'],
        'in N':['in N'],
        'into N':['into N'],
        'of N':['of N'],
        'on N':['on N'],
        'out of N':['out of N'],
        'to N':['to N'],
        'under N':['under N'],
        'with N':['with N'],
        'within N':['within N'],
        'without N':['without N'],
    },
    'ADJ':{
        # The patterns of graded adjectives.
        'adv ADJ':['adv ADJP'],
        'adv ADJ n':['adv ADJ sth'],
        'as ADJ as n/-ing':['as ADJP as sth', 'as ADJP as doing'],
        'as ADJ as adj/adv':['as ADJP as adjp', 'as ADJP as advp'],
        'as ADJ as num/amount':['as ADJP as amount'],
        'as ADJ as cl':['as ADJP as clause'],
        'ADJ enough':['ADJP enough'],
        'ADJ enough to-inf':['ADJP enough to inf'],
        'ADJ enough for n':['ADJP enough for sth'],
        'ADJ enough for n to-inf':['ADJP enough for sth to inf'],
        'ADJ enough that':['ADJP enough that'],
        'ADJ enough n':['ADJP enough sth'],
        'ADJ enough n to-inf':['ADJP enough sth to inf'],
        'ADJ enough n for n':['ADJP enough sth for sth'],
        'ADJ enough n for n to-inf':['ADJP enough sth for sth to inf'],        
        'ADJ enough n that':['ADJP enough sth that'],
        'how ADJ':['how ADJP'],
        'how ADJ v-link n':['how ADJP v-link sth'],
        'how ADJ n v-link':['how ADJP sth v-link'],
        'how ADJ it v-link that':['how ADJP it v-link that'],
        'how ADJ it v-link to-inf':['how ADJP it v-link to inf'],
        'how ADJ to-inf':['how ADJ to inf'],
        'how ADJ cl':['how ADJP clause'],        
        'how ADJ a n cl':['how ADJP a sth clause'],
        'however ADJ':['however ADJP'],
        'however ADJ n':['however ADJ sth'],
        'however ADJ n v-link':['however ADJP sth v-link'],
        'so ADJ that':['so ADJP that'],
        'so ADJ as to-inf':['so ADJP as to inf'],
        'such a ADJ n that':['such a ADJ sth that'],
        'such ADJ n that':['such ADJ sth that'],        
        'too ADJ to-inf':['too ADJP to inf'],
        'too ADJ for n':['too ADJ for sth'],
        'too ADJ for n to-inf':['too ADJ for sth to inf'],
        'the ADJER':['the ADJERP', 'the ADJER sth'],
        # 'the ADJER of pl-n' :['the ADJER of sth+s'],
        'the ADJER of n' :['the ADJERP of sth'],
        'ADJER than n/-ing':['ADJERP than sth', 'ADJERP than doing'],
        'ADJER than cl':['ADJERP than clause'],
        'ADJER than adv':['ADJERP than advp'],
        'ADJER than adj/-ed':['ADJERP than adjp', 'ADJERP than done'],
        'ADJER than prep':['ADJERP than prep'],
        'ADJER than adj/-ed n':['ADJERP than adj sth', 'ADJERP than done sth'],
        # 'ADJER than someway':['ADJER than someway'],
        'ADJER n than n':['ADJER sth than sth'],
        'ADJER n than prep':['ADJER sth than prep'],
        'ADJER n than cl':['ADJER sth than clause'],
        # 'the ADJER n, the ADJ n'
        # 'the ADJER, the ADJER'
        # The Patterns of superlative adjectives.
        'one of the/poss ADJEST':["one of the ADJESTP", "one of the ADJEST", "one of one's ADJESTP", "one of one's ADJEST"],
        'the ADJEST n to-inf':['the ADJEST sth to inf'],
        # 'the ADJEST someway':['the ADJEST someway'],
        # 'the ADJEST adj sth':['the ADJEST adj sth'],
        'the ADJEST n rel-cl':['the ADJEST sth clause'],
        'the/poss ADJEST n since':['the ADJEST sth since', "one's ADJEST sth since"],
        'the/poss ADJEST n prep':['the ADJEST sth prep', "one's ADJEST sth prep"],
        'the ADJEST n adj/adv':['the ADJEST sth adjp', 'the ADJEST sth advp'],
        # 'the ADJEST of something+s':['the ADJEST of something+s'],
        # 'the ADJEST among something+s':['the ADJEST among something+s'],
        'the ADJEST of/among n':['the ADJESTP of sth', 'the ADJESTP among sth'],
        'the ADJEST adj n':['the ADJEST adj sth'],
        'the ADJEST adv n':['the ADJEST adv sth'],
        'the ADJEST to-inf':['the ADJESTP to inf'],
        'the ADJEST rel-cl':['the ADJESTP clause'],
        'the ADJEST since':['the ADJESTP since'],
        'the ADJEST prep':['the ADJEST prep'],
        'the ADJEST adj/adv':['the ADJEST adjp', 'the ADJEST advp'],
        # 'the/poss ADJEST':["the ADJESTP", "one's ADJESTP"],
        'at poss ADJEST':["at one's ADJESTP"],
        'ADJ n':['ADJ sth'],
        # 'det ADJ n':['det ADJ sth'],
        'a ADJ amount':['det ADJ amount'],
        'v-link ADJ':['v-link ADJP'],
        'v n ADJ':['do sth ADJP'],
        'be v-ed ADJ':['be done ADJP'],
        'v n as ADJ':['do sth as ADJP'],
        'be v-ed as ADJ':['be done as ADJP'],
        # 'v ADJ':['ADJ after doing'],
        'v ADJ at amount':['do ADJP at amount'],
        'v ADJ in n':['do ADJP in sth'],
        'n ADJ':['sth ADJP'],
        'amount ADJ':['amount ADJP'],
        # 'n ord ADJ':['sth ord ADJP'],
        # 'num ADJ':['amount ADJ'],
        'ADJ that':['ADJP that'],
        'ADJ wh':['ADJP wh'],
        'ADJ to-inf':['ADJP to inf'],
        'ADJ n to-inf':['ADJ sth to inf'],
        'ADJ -ing':['ADJP doing'],
        # 'ADJ about n':['ADJP about sth', 'ADJP about doing', 'ADJP about wh'],
        'ADJ about n':['ADJP about sth'],
        'ADJ about -ing':['ADJP about doing'],
        'ADJ about wh':['ADJP about wh'],
        'ADJ against n':['ADJP against sth'],
        'ADJ as n':['ADJP as sth'],
        'the ADJ as n':['the ADJP as sth'],
        'ADJ as to wh':['ADJP as to wh'],
        'ADJ as to n':['ADJP as to sth'],
        # 'ADJ at n':['ADJP at sth', 'ADJP at doing'],
        'ADJ at n':['ADJP at sth'],
        'ADJ at -ing':['ADJP at doing'],
        # 'ADJ between pl-n':['ADJ between sth+s'],
        'ADJ between n':['ADJP between sth'],
        'ADJ by n':['ADJP by sth'],
        # 'ADJ for n':['ADJP for sth', 'ADJP for doing'],
        'ADJ for n':['ADJP for sth'],
        'ADJ for -ing':['ADJP for doing'],
        'ADJ for n to-inf':['ADJP for sth to inf'],        
        'ADJ n for n':['ADJP sth for sth'],
        'ADJ from n':['ADJP from sth'],
        'ADJ from n to n':['ADJP from sth to sth'],
        # 'ADJ in n':['ADJP in sth', 'ADJP in doing'],
        'ADJ in n':['ADJP in sth'],
        'ADJ in -ing':['ADJP in doing'],
        # 'ADJ in colour':['ADJP in colour'],
        'ADJ in n as n':['ADJP in sth as sth'],
        'ADJ in n from n':['ADJP in sth from sth'],
        'ADJ in n to n':['ADJP in sth to sth'],
        'ADJ in n with n':['ADJP in sth with sth'],
        # 'ADJ of n':['ADJP of sth', 'ADJP of doing', 'ADJP of wh'],
        'ADJ of n':['ADJP of sth'],
        'ADJ of -ing':['ADJP of doing'],
        'ADJ of wh':['ADJP of wh'],
        'v n ADJ of n':['do sth ADJP of sth'],
        # 'ADJ on n':['ADJP on sth', 'ADJP on doing', 'ADJP on wh'],
        'ADJ on n':['ADJP on sth'],
        'ADJ on -ing':['ADJP on doing'],
        'ADJ on wh':['ADJP on wh'],
        'ADJ on/upon n for n':['ADJP on sth for sth', 'ADJP upon sth for sth'],
        'ADJ on/upon n to-inf':['ADJP on sth to inf', 'ADJP upon sth to inf'],
        'ADJ over n':['ADJP over sth'],
        # 'ADJ to n':['ADJP to sth', 'ADJP to doing'],
        'ADJ to n':['ADJP to sth'],
        'ADJ to -ing':['ADJP to doing'],
        'ADJ to n for n/-ing':['ADJP to sth for sth', 'ADJP to sth for doing'],
        # 'ADJ towards/toward n':['ADJP towards sth', 'ADJP toward sth', 'ADJP towards doing', 'ADJP toward doing'],
        'ADJ towards/toward n':['ADJP towards sth', 'ADJP toward sth'],
        'ADJ towards/toward -ing':['ADJP towards doing', 'ADJP toward doing'],
        # 'ADJ with n':['ADJP with sth', 'ADJP with doing'],
        'ADJ with n':['ADJP with sth'],
        'ADJ with -ing':['ADJP with doing'],
        # 'ADJ onto doing n':['ADJ onto doing sth'],
        'it v-link ADJ that':['it v-link ADJP that'],
        'it v-link ADJ for n that':['it v-link ADJP for sth that'],
        'it v-link ADJ of n that':['it v-link ADJP of sth that'],
        'it v-link ADJ to n that':['it v-link ADJP to sth that'],
        'it v n ADJ that':['it do sth ADJP that'],
        'it v n as ADJ that':['it do sth as ADJP that'],
        'it v-link ADJ wh':['it v-link ADJP wh'],
        # 'it v-link ADJ what':['it v-link ADJP what'],
        # 'it v-link ADJ how':['it v-link ADJP how'],
        # 'it v-link ADJ when':['it v-link ADJP when'],
        # 'it v-link ADJ if':['it v-link ADJP if'],
        'it v-link ADJ to-inf':['it v-link ADJP to inf'],
        'it v-link ADJ for n to-inf':['it v-link ADJP for sth to inf'],
        'it v-link ADJ of n to-inf':['it v-link ADJP of sth to inf'],        
        'it v n ADJ to-inf':['it do sth ADJ to inf'],        
        'it v-link ADJ -ing':['it v-link ADJ doing'],
        # 'it does NOUN to do n':['it does N to do n'],
        'v it ADJ that':['do it ADJP that'],
        'it be v-ed ADJ that':['it be done ADJP that'],        
        'v it as ADJ that':['do it as ADJP that'],
        'v it ADJ to-inf':['do it ADJP to inf'],
        'v it ADJ for n to-inf':['do it ADJP for sth to inf'],
        'v it as ADJ to-inf':['do it as ADJP to inf'],
        'it v-link ADJ about n':['it v-link ADJP about sth'],
        'there v-link -thing ADJ about n/-ing':['there be -thing ADJP about sth', 'there be -thing ADJP about doing'],
        'v -thing ADJ about n':['do -thing ADJP about sth'],
        'there v-link -thing ADJ in n/-ing':['there be -thing ADJP in sth', 'there be -thing ADJP in doing'],
        'v -thing ADJ in n':['do -thing ADJP in sth'],        
        'there v-link -thing ADJ with n/-ing':['there be -thing ADJP with sth', 'there be -thing ADJP with doing'],
        'v -thing ADJ with n':['do -thing ADJP with sth'],
        '-thing v-link ADJ with n':['-thing v-link ADJP with sth'],
        # Adjective patterns with what.
        'what v-link ADJ v-link that/wh':['what v-link ADJP v-link that', 'what v-link ADJP v-link wh'],
        'what v-link ADJ v-link -ing':['what v-link ADJP v-link doing'],
        'what v-link ADJ to n v-link that/wh':['what v-link ADJP to sth v-link that', 'what v-link ADJP to sth v-link wh'],        
        'what v-link ADJ about n v-link n/that/wh':['what v-link ADJP about sth v-link n', 'what v-link ADJP about sth v-link that',
                                                    'what v-link ADJP about sth v-link wh'],
        'what v-link ADJ in n v-link n/that/wh':['what v-link ADJP in sth v-link n', 'what v-link ADJP in sth v-link that',
                                                 'what v-link ADJP in sth v-link wh'],
        'what v-link ADJ with n v-link n/that/wh':['what v-link ADJP with sth v-link n', 'what v-link ADJP with sth v-link that',
                                                   'what v-link ADJP with sth v-link wh'],
        # Combining forms
        # 'ADJ adj':['ADJ adj'],
        # 'ADJ and adj':['ADJ and adj'],
    }
}

# PGPatterns = dict([(x, True) for x in PGlist.split('\n')])
Keywordpos = set(['V', 'V-ed', 'N', "N's", 'ADJ', 'ADJER', 'ADJEST', 'ADJP', 'ADJERP', 'ADJESTP'])
Pos_map = {'V':'V', 'V-ed':'V', 'N':'N', "N's":'N', 'ADJ':'ADJ', 'ADJER':'ADJ', 'ADJEST':'ADJ', 'ADJP':'ADJ', 'ADJERP':'ADJ', 'ADJESTP':'ADJ'}
Pat_poslen = defaultdict(lambda:defaultdict(list))
Pat_map = {}
for pos in PGtable:
    for pg, pats in PGtable[pos].iteritems():
        for pat in pats:
            if pat.count(' ')+1 <= 5:
                try:
                    pos = (set(pat.split()) & Keywordpos).pop()
                    Pat_poslen[pos][(pat.count(' ')+1, pat.split(' ').index(pos))].append(pat.strip())
                except:
                    print pat
                Pat_map[pat] = pg

